'use client';
import { useState, useEffect } from 'react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { 
  FaDownload, FaEye, FaFilter, FaCalendarAlt, FaChartBar, FaFilePdf, 
  FaFileExcel, FaPrint, FaSearch, FaSort, FaUniversity,
  FaExclamationTriangle, FaCheckCircle, FaClock, FaUsers, FaInfoCircle
} from 'react-icons/fa';

const reportTypes = ['All', 'Compliance', 'Analytics', 'Audit', 'Survey', 'Minutes'];
const statusTypes = ['All', 'Generated', 'Pending', 'In Review'];
const priorityTypes = ['All', 'Critical', 'High', 'Medium', 'Low'];

export default function UniversityReports() {
  // --- States ---
  const [reports, setReports] = useState([]); 
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [universityStats, setUniversityStats] = useState({
    totalColleges: 0,
    compliantColleges: 0,
    totalCases: 0,
    resolvedCases: 0,
    avgComplianceRate: '0%'
  });

  const [searchTerm, setSearchTerm] = useState('');
  const [selectedType, setSelectedType] = useState('All');
  const [selectedStatus, setSelectedStatus] = useState('All');
  const [selectedPriority, setSelectedPriority] = useState('All');
  const [sortBy, setSortBy] = useState('date');
  const [sortOrder, setSortOrder] = useState('desc');
  const [selectedReport, setSelectedReport] = useState(null);

  // --- NEW: Global PDF Export Logic ---
  const handleGenerateGlobalReport = () => {
    const doc = new jsPDF();
    
    // Header
    doc.setFillColor(24, 24, 27); // Dark Zinc
    doc.rect(0, 0, 210, 40, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.text("UNIVERSITY GLOBAL SUMMARY REPORT", 14, 22);
    doc.setFontSize(10);
    doc.text(`Generated Date: ${new Date().toLocaleDateString()}`, 14, 32);

    // Stats Table
    autoTable(doc, {
      startY: 45,
      head: [['Metric', 'Value']],
      body: [
        ['Total Affiliated Colleges', universityStats.totalColleges.toString()],
        ['Compliant Colleges', universityStats.compliantColleges.toString()],
        ['Total Reported Cases', universityStats.totalCases.toString()],
        ['Resolved Cases', universityStats.resolvedCases.toString()],
        ['Average Compliance Rate', universityStats.avgComplianceRate],
      ],
      theme: 'grid',
      headStyles: { fillColor: [249, 115, 22] } // Orange
    });

    // Reports Table Summary
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(14);
    doc.text("Active Reports Summary", 14, doc.lastAutoTable.finalY + 15);

    const tableData = sortedReports.map(r => [
      r.title,
      r.type,
      r.status,
      r.priority,
      r.dateGenerated
    ]);

    autoTable(doc, {
      startY: doc.lastAutoTable.finalY + 20,
      head: [['Title', 'Type', 'Status', 'Priority', 'Date']],
      body: tableData,
      headStyles: { fillColor: [30, 30, 30] }
    });

    doc.save("University_Global_Report.pdf");
  };

  // --- Individual PDF Export Logic ---
  const handleDownloadPDF = (report) => {
    const doc = new jsPDF();
    const collegeName = report.collegeName || report.college_name || report.college || "University-wide";
    
    doc.setFillColor(249, 115, 22); 
    doc.rect(0, 0, 210, 40, 'F');
    doc.setFontSize(20);
    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.text("UNIVERSITY COMPLIANCE REPORT", 14, 20);
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Report ID: ${report.id} | Generated: ${new Date().toLocaleDateString()}`, 14, 30);
    
    autoTable(doc, {
      startY: 50,
      head: [['CATEGORY', 'REPORT DETAILS']],
      body: [
        ['REPORT TITLE', (report.title || 'N/A').toUpperCase()],
        ['COLLEGE / INSTITUTION', collegeName.toUpperCase()],
        ['REPORT TYPE', report.type || 'N/A'],
        ['PRIORITY LEVEL', report.priority || 'N/A'],
        ['COMPLIANCE RATE', report.complianceRate || '0%'],
        ['TOTAL CASES', (report.totalCases || 0).toString()],
        ['RESOLVED CASES', (report.resolvedCases || 0).toString()],
        ['GENERATED BY', report.generatedBy || 'System Admin'],
        ['DATE GENERATED', report.dateGenerated || 'N/A'],
        ['STATUS', (report.status || 'PENDING').toUpperCase()],
      ],
      theme: 'striped',
      headStyles: { fillColor: [30, 30, 30], textColor: [255, 255, 255], fontStyle: 'bold' },
      styles: { fontSize: 10, cellPadding: 5 },
      columnStyles: {
        0: { fontStyle: 'bold', textColor: [100, 100, 100], cellWidth: 60 },
        1: { fontStyle: 'bold', textColor: [20, 20, 20] },
      }
    });

    if (report.description) {
        const finalY = doc.lastAutoTable.finalY + 10;
        doc.setFontSize(10);
        doc.setTextColor(100, 100, 100);
        doc.text("Description/Notes:", 14, finalY);
        doc.setFont('helvetica', 'italic');
        doc.text(report.description, 14, finalY + 7, { maxWidth: 180 });
    }

    doc.save(`${collegeName.replace(/\s+/g, '_')}_Report.pdf`);
  };

  // --- Real Fetch Logic ---
  const loadData = async () => {
    try {
      setLoading(true);
      setError(null);
      const token = localStorage.getItem('token');
      
      const response = await fetch('http://127.0.0.1:8000/api/university/reports-dashboard/', {
        method: 'GET',
        headers: {
          'Authorization': `Token ${token}`,
          'Content-Type': 'application/json'
        }
      });

      if (!response.ok) throw new Error(`Server Error: ${response.status}`);
      const data = await response.json();
      
      if (data.status === 'success') {
        setReports(data.reports || []);
        setUniversityStats(data.summary || {
          totalColleges: 0, compliantColleges: 0, totalCases: 0, resolvedCases: 0, avgComplianceRate: '0%'
        });
      } else {
        throw new Error(data.message || "Failed to fetch data");
      }
    } catch (err) {
      console.error("Fetch Error:", err);
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadData();
  }, []);

  // --- Filter & Sort Logic ---
  const filteredReports = reports.filter(report => {
    const college = report.collegeName || report.college_name || report.college || "";
    const matchesSearch = (report.title || "").toLowerCase().includes(searchTerm.toLowerCase()) ||
                          (report.description || "").toLowerCase().includes(searchTerm.toLowerCase()) ||
                          (college).toLowerCase().includes(searchTerm.toLowerCase());
    const matchesType = selectedType === 'All' || report.type === selectedType;
    const matchesStatus = selectedStatus === 'All' || report.status === selectedStatus;
    const matchesPriority = selectedPriority === 'All' || report.priority === selectedPriority;
    return matchesSearch && matchesType && matchesStatus && matchesPriority;
  });

  const sortedReports = [...filteredReports].sort((a, b) => {
    let aValue, bValue;
    if (sortBy === 'title') { aValue = (a.title || "").toLowerCase(); bValue = (b.title || "").toLowerCase(); }
    else if (sortBy === 'date') { aValue = new Date(a.dateGenerated); bValue = new Date(b.dateGenerated); }
    else if (sortBy === 'priority') {
      const pOrder = { 'Critical': 4, 'High': 3, 'Medium': 2, 'Low': 1 };
      aValue = pOrder[a.priority] || 0; bValue = pOrder[b.priority] || 0;
    } else { aValue = a.collegesCovered || 0; bValue = b.collegesCovered || 0; }
    return sortOrder === 'asc' ? (aValue > bValue ? 1 : -1) : (aValue < bValue ? 1 : -1);
  });

  const handleSort = (column) => {
    if (sortBy === column) setSortOrder(sortOrder === 'asc' ? 'desc' : 'asc');
    else { setSortBy(column); setSortOrder('desc'); }
  };

  const getStatusIcon = (status) => {
    if (status === 'Generated') return <FaCheckCircle className="text-green-500" />;
    if (status === 'Pending') return <FaClock className="text-orange-500" />;
    return <FaExclamationTriangle className="text-blue-500" />;
  };

  const getPriorityBadge = (priority) => {
    const styles = {
      Critical: 'bg-red-100 text-red-800 border-red-200',
      High: 'bg-orange-100 text-orange-800 border-orange-200',
      Medium: 'bg-yellow-100 text-yellow-800 border-yellow-200',
      Low: 'bg-green-100 text-green-800 border-green-200'
    };
    return styles[priority] || 'bg-gray-100 text-gray-800';
  };

  if (loading) return <div className="p-20 text-center text-orange-600 font-bold animate-pulse">Loading University Data...</div>;

  if (error) return (
    <div className="p-10 text-center">
      <p className="text-red-600 font-bold text-xl">Backend Connection Failed</p>
      <p className="text-gray-500 mb-4">{error}</p>
      <button onClick={loadData} className="bg-orange-500 text-white px-6 py-2 rounded-lg shadow-lg">Retry Connection</button>
    </div>
  );

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between">
        <div>
          <h1 className="text-2xl md:text-3xl font-bold text-gray-900 uppercase">University Reports</h1>
          <p className="text-gray-600 mt-1">Real-time analytics for affiliated colleges</p>
        </div>
        <button 
          onClick={handleGenerateGlobalReport}
          className="mt-4 md:mt-0 flex items-center space-x-2 bg-zinc-900 hover:bg-orange-600 text-white px-6 py-3 rounded-xl transition-all shadow-md font-bold text-sm uppercase"
        >
          <FaChartBar /> <span>Generate Global Report</span>
        </button>
      </div>

      {/* Stats Cards */}
      <div className="grid grid-cols-2 md:grid-cols-5 gap-4">
        {[
          { label: 'Total Colleges', val: universityStats.totalColleges, color: 'text-blue-600', icon: <FaUniversity /> },
          { label: 'Compliant', val: universityStats.compliantColleges, color: 'text-green-600', icon: <FaCheckCircle /> },
          { label: 'Total Cases', val: universityStats.totalCases, color: 'text-orange-600', icon: <FaExclamationTriangle /> },
          { label: 'Resolved', val: universityStats.resolvedCases, color: 'text-purple-600', icon: <FaCheckCircle /> },
          { label: 'Avg Rate', val: universityStats.avgComplianceRate, color: 'text-teal-600', icon: <FaChartBar /> }
        ].map((item, i) => (
          <div key={i} className="bg-white rounded-xl shadow-sm border border-orange-50 p-4 hover:shadow-md transition-shadow">
            <div className="flex justify-between items-start mb-2">
                <span className={`text-xl font-bold ${item.color}`}>{item.val}</span>
                <span className={`${item.color} opacity-20 text-lg`}>{item.icon}</span>
            </div>
            <div className="text-[10px] text-gray-400 mt-1 uppercase font-black tracking-wider leading-none">{item.label}</div>
          </div>
        ))}
      </div>

      {/* Filters */}
      <div className="bg-white rounded-xl shadow-sm border border-orange-100 p-4">
        <div className="grid grid-cols-1 md:grid-cols-5 gap-3">
          <div className="md:col-span-2 relative">
            <FaSearch className="absolute left-3 top-1/2 -translate-y-1/2 text-orange-400" />
            <input type="text" placeholder="Search reports..." value={searchTerm} onChange={(e) => setSearchTerm(e.target.value)} className="w-full pl-10 pr-4 py-2 border border-orange-100 rounded-lg bg-orange-50/50 outline-none focus:ring-2 focus:ring-orange-500 text-sm font-medium" />
          </div>
          <select value={selectedType} onChange={(e) => setSelectedType(e.target.value)} className="text-xs font-bold uppercase p-2 border border-orange-100 rounded-lg outline-none bg-white">
            {reportTypes.map(t => <option key={t} value={t}>{t === 'All' ? 'All Types' : t}</option>)}
          </select>
          <select value={selectedStatus} onChange={(e) => setSelectedStatus(e.target.value)} className="text-xs font-bold uppercase p-2 border border-orange-100 rounded-lg outline-none bg-white">
            {statusTypes.map(s => <option key={s} value={s}>{s === 'All' ? 'All Status' : s}</option>)}
          </select>
          <select value={selectedPriority} onChange={(e) => setSelectedPriority(e.target.value)} className="text-xs font-bold uppercase p-2 border border-orange-100 rounded-lg outline-none bg-white">
            {priorityTypes.map(p => <option key={p} value={p}>{p === 'All' ? 'All Priority' : p}</option>)}
          </select>
        </div>
      </div>

      {/* Table */}
      <div className="bg-white rounded-2xl shadow-sm border border-orange-100 overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-left">
            <thead className="bg-orange-600 text-[11px] font-black text-white uppercase tracking-wider">
              <tr>
                <th className="p-4 cursor-pointer" onClick={() => handleSort('title')}>Report Title <FaSort className="inline ml-1 opacity-50" /></th>
                <th className="p-4">Type</th>
                <th className="p-4 text-center">Status</th>
                <th className="p-4 text-center">Priority</th>
                <th className="p-4">Colleges</th>
                <th className="p-4">Date</th>
                <th className="p-4 text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="text-sm divide-y divide-orange-50">
              {sortedReports.map((report) => (
                <tr key={report.id} className="hover:bg-orange-50/50 transition-colors group">
                  <td className="p-4">
                    <div className="flex items-center space-x-3">
                      {report.format === 'PDF' ? <FaFilePdf className="text-red-500 text-lg" /> : <FaFileExcel className="text-green-600 text-lg" />}
                      <div>
                        <span className="font-bold text-gray-800 block leading-none mb-1 group-hover:text-orange-600 transition-colors">{report.title}</span>
                        <span className="text-[10px] text-gray-400 uppercase font-black tracking-tighter">{report.fileSize} • {report.format}</span>
                      </div>
                    </div>
                  </td>
                  <td className="p-4"><span className="px-2 py-1 bg-zinc-100 text-zinc-700 rounded text-[9px] font-black uppercase border border-zinc-200">{report.type}</span></td>
                  <td className="p-4">
                    <div className="flex items-center justify-center space-x-1.5 font-bold text-[10px] uppercase text-gray-600">
                        {getStatusIcon(report.status)}
                        <span>{report.status}</span>
                    </div>
                  </td>
                  <td className="p-4 text-center"><span className={`px-2 py-0.5 rounded-full text-[9px] font-black uppercase border ${getPriorityBadge(report.priority)}`}>{report.priority}</span></td>
                  <td className="p-4">
                    <div className="flex items-center gap-1 font-bold text-gray-800">
                        <FaUniversity className="text-orange-400" /> {report.collegesCovered || 1}
                    </div>
                  </td>
                  <td className="p-4 text-gray-500 font-bold text-xs">{report.dateGenerated}</td>
                  <td className="p-4">
                    <div className="flex justify-end space-x-2">
                        <button 
                          onClick={() => setSelectedReport(report)} 
                          className="p-2.5 bg-zinc-900 text-white hover:bg-orange-600 rounded-xl transition-all shadow-sm"
                        >
                          <FaEye size={14} />
                        </button>
                        <button 
                          onClick={() => handleDownloadPDF(report)}
                          className="p-2.5 bg-white border border-orange-200 text-orange-500 hover:bg-orange-50 rounded-xl transition-all"
                        >
                          <FaDownload size={14} />
                        </button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* --- Detailed Modal --- */}
      {selectedReport && (
        <div className="fixed inset-0 bg-zinc-950/80 backdrop-blur-sm flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-3xl max-w-2xl w-full p-0 shadow-2xl overflow-hidden animate-in fade-in zoom-in duration-200">
            <div className="bg-orange-600 p-6 text-white flex justify-between items-start">
              <div>
                <div className="flex items-center gap-2 mb-1">
                    <FaInfoCircle />
                    <span className="text-[10px] font-black uppercase tracking-widest opacity-80">University Archive</span>
                </div>
                <h3 className="text-xl font-black uppercase leading-tight">{selectedReport.title}</h3>
              </div>
              <button onClick={() => setSelectedReport(null)} className="bg-white/10 p-2 rounded-lg hover:bg-white/20 transition-all font-bold text-xl">&times;</button>
            </div>

            <div className="p-8">
                <div className="flex items-center gap-4 mb-6 p-4 bg-orange-50 rounded-2xl border-2 border-orange-100 shadow-sm">
                  <div className="bg-orange-600 p-3 rounded-xl text-white">
                    <FaUniversity size={20} />
                  </div>
                  <div>
                    <p className="text-[10px] uppercase font-black text-orange-400 tracking-widest leading-none mb-1">Institution</p>
                    <p className="text-lg font-bold text-zinc-900 leading-tight uppercase">
                      {selectedReport.collegeName || selectedReport.college_name || selectedReport.college || "Global University Data"}
                    </p>
                  </div>
                </div>

                <div className="grid grid-cols-3 gap-4 mb-8">
                    <div className="bg-zinc-50 border border-zinc-100 p-4 rounded-2xl text-center">
                        <div className="text-2xl font-black text-zinc-900 leading-none">{selectedReport.totalCases || 0}</div>
                        <div className="text-[9px] text-gray-400 uppercase font-black mt-1 tracking-wider">Cases</div>
                    </div>
                    <div className="bg-green-50 border border-green-100 p-4 rounded-2xl text-center">
                        <div className="text-2xl font-black text-green-600 leading-none">{selectedReport.resolvedCases || 0}</div>
                        <div className="text-[9px] text-green-400 uppercase font-black mt-1 tracking-wider">Resolved</div>
                    </div>
                    <div className="bg-orange-50 border border-orange-100 p-4 rounded-2xl text-center">
                        <div className="text-2xl font-black text-orange-600 leading-none">{selectedReport.complianceRate || '0%'}</div>
                        <div className="text-[9px] text-orange-400 uppercase font-black mt-1 tracking-wider">Rate</div>
                    </div>
                </div>

                <div className="grid grid-cols-2 gap-y-6 gap-x-12 mb-8 px-2">
                    {[
                        { label: 'Generated By', val: selectedReport.generatedBy || 'System Admin', icon: <FaUsers className="text-orange-500" /> },
                        { label: 'Date Range', val: selectedReport.dateRange || 'Current Academic Year', icon: <FaCalendarAlt className="text-orange-500" /> },
                        { label: 'File Format', val: selectedReport.format, icon: selectedReport.format === 'PDF' ? <FaFilePdf className="text-red-500" /> : <FaFileExcel className="text-green-500" /> },
                        { label: 'Priority', val: selectedReport.priority, icon: <FaExclamationTriangle className="text-orange-500" /> }
                    ].map((item, idx) => (
                        <div key={idx} className="flex items-center gap-3">
                            <div className="text-lg">{item.icon}</div>
                            <div>
                                <p className="text-[9px] uppercase font-black text-gray-400 tracking-tighter">{item.label}</p>
                                <p className="text-sm font-bold text-zinc-800 uppercase">{item.val}</p>
                            </div>
                        </div>
                    ))}
                </div>

                <div className="bg-gray-50 p-5 rounded-2xl border border-gray-100 mb-8">
                    <p className="text-xs text-gray-600 leading-relaxed font-medium italic border-l-4 border-orange-500 pl-4 uppercase">
                        {selectedReport.description || 'Institutional compliance monitoring and case resolution summary.'}
                    </p>
                </div>

                <div className="flex space-x-4">
                    <button onClick={() => setSelectedReport(null)} className="flex-1 py-4 text-xs font-black text-gray-400 hover:text-zinc-900 transition-colors uppercase tracking-[0.2em]">Dismiss</button>
                    <button 
                      onClick={() => handleDownloadPDF(selectedReport)}
                      className="flex-1 bg-zinc-900 hover:bg-orange-600 text-white py-4 rounded-2xl font-black shadow-lg flex items-center justify-center gap-2 uppercase text-[10px] tracking-[0.2em] transition-all"
                    >
                        <FaDownload /> Export PDF Record
                    </button>
                </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}