# Generated by Django 5.2.8 on 2026-01-26 06:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='universityprofile',
            options={'verbose_name': 'University Profile', 'verbose_name_plural': 'University Profiles'},
        ),
        migrations.AddField(
            model_name='universityprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universityprofile',
            name='city',
            field=models.CharField(default='Ahmedabad', max_length=100),
        ),
        migrations.AddField(
            model_name='universityprofile',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='universityprofile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='universityprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='universityprofile',
            name='established_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universityprofile',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='universityprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='university_logos/'),
        ),
        migrations.AddField(
            model_name='universityprofile',
            name='university_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='universityprofile',
            name='vice_chancellor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='universityprofile',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
