# Generated by Django 5.2.8 on 2026-02-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_alter_universityprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='universityprofile',
            name='accreditation_grade',
            field=models.CharField(blank=True, default='NAAC A++', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='universityprofile',
            name='official_grade',
            field=models.CharField(blank=True, default='A++', max_length=20, null=True),
        ),
    ]
