# Generated by Django 6.0.3 on 2026-04-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_universityprofile_accreditation_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='universityprofile',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
