# Generated by Django 6.0.3 on 2026-04-04 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_universityprofile_email_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universityprofile',
            name='email_notifications',
        ),
    ]
