# Generated by Django 5.2.8 on 2026-01-21 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collage', '0002_committeemember'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegeprofile',
            name='alternate_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='collegeprofile',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
