# Generated by Django 5.2.8 on 2026-01-26 06:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collage', '0003_collegeprofile_alternate_contact_and_more'),
        ('university', '0002_alter_universityprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegeprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collegeprofile',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliated_colleges', to='university.universityprofile'),
        ),
        migrations.AddField(
            model_name='collegeprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
