# Generated by Django 5.2.8 on 2026-01-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_remove_studentprofile_id_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='anonymous_reporting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='newsletter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='push_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='security_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='two_factor_auth',
            field=models.BooleanField(default=False),
        ),
    ]
