# Generated by Django 5.2.8 on 2026-01-13 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_collegeprofile_report_college_assigned_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='college_assigned',
        ),
        migrations.RemoveField(
            model_name='universityprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='CollegeProfile',
        ),
        migrations.DeleteModel(
            name='UniversityProfile',
        ),
    ]
