# Generated by Django 5.2.8 on 2026-01-13 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collage', '0001_initial'),
        ('student', '0008_remove_report_college_assigned_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='student',
            new_name='user',
        ),
        migrations.AddField(
            model_name='report',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='college_reports', to='collage.collegeprofile'),
        ),
    ]
