# Generated by Django 5.2.8 on 2026-02-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_rename_student_report_user_report_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='evidence_audio',
            field=models.FileField(blank=True, null=True, upload_to='evidence/audio/'),
        ),
        migrations.AddField(
            model_name='report',
            name='evidence_image',
            field=models.ImageField(blank=True, null=True, upload_to='evidence/images/'),
        ),
        migrations.AddField(
            model_name='report',
            name='evidence_video',
            field=models.FileField(blank=True, null=True, upload_to='evidence/videos/'),
        ),
    ]
