# Generated by Django 5.2.8 on 2026-03-14 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_report_evidence_audio_report_evidence_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_seen_by_student',
            field=models.BooleanField(default=True),
        ),
    ]
