# Generated by Django 5.2.8 on 2026-03-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_report_is_seen_by_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_read_by_college',
            field=models.BooleanField(default=False),
        ),
    ]
